# Generated by Django 4.1 on 2022-08-19 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0002_movie_genres"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.IntegerField()),
                ("review", models.TextField(blank=True, null=True)),
                ("spoilers", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "recomendation",
                    models.CharField(
                        choices=[
                            ("Must watch", "Must Watch"),
                            ("Should watch", "Should Watch"),
                            ("Avoid watch", "Avoid Watch"),
                            ("No opinion", "No Opinion"),
                        ],
                        default="No opinion",
                        max_length=50,
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
