# Generated by Django 4.1 on 2022-09-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_rename_user_review_critic_alter_review_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.TextField(default="", unique=True),
            preserve_default=False,
        ),
    ]
